### ISSUE TITLE
DI란?

### ISSUE THREAD

**Issue by dev-donghwan** [junieberry/Android-Baby-Study#1]
keyword : SOLID, Dependency Injection, 의존성 주입

**Comment by jionchu** [comment]
https://jionchu.tistory.com/123

**Comment by dev-donghwan** [comment]
> keyword : SOLID, Dependency Injection, 의존성 주입

**Comment by junieberry** [comment]
https://junieberry.github.io/android/2021-09-01-DI.html

**Comment by ashwon12** [comment]
https://velog.io/@ashwon1218/DIDependency-injection-%EB%9E%80
넘 늦어서 죄송합니닷,,,😿
