### ISSUE TITLE
MVC vs MVP vs MVVM

### ISSUE THREAD

**Issue by dev-donghwan** [junieberry/Android-Baby-Study#2]
keyword : Architecture Pattern in Android, MVC, MVP, MVVM

**Comment by junieberry** [comment]
https://junieberry.github.io/android/2021-09-02-MVC,MVP,MVVM.html

부족한 부분 말씀해주시면 공부해서 추가하겠습니다~~~🤓

**Comment by ashwon12** [comment]
https://velog.io/@ashwon1218/%EC%95%88%EB%93%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-%EC%95%84%ED%82%A4%ED%85%8D%EC%B2%98-%ED%8C%A8%ED%84%B4MVCMVPMVVM

**Comment by jionchu** [comment]
https://jionchu.tistory.com/entry/Android-Architectural-Pattern-MVC-MVP-MVVM
