### ISSUE TITLE
LiveData

### ISSUE THREAD

**Issue by dev-donghwan** [junieberry/Android-Baby-Study#3]
keyword : observable pattern, livedata

**Comment by ashwon12** [comment]
https://velog.io/@ashwon1218/Android-Jetpack-LiveData%EB%A5%BC-%EC%95%8C%EC%95%84%EB%B3%B4%EC%9E%90

**Comment by dev-donghwan** [comment]
@ashwon12 
https://medium.com/harrythegreat/jetpack-android-livedata-%EC%95%8C%EC%95%84%EB%B3%B4%EA%B8%B0-ed49a6f17de3


참고해서 Lifecycle이랑 관계 보시면 좋을거같아요.
그리고 추가적으로 ObservableField랑 LiveData의 차이가 뭔지 알아두시면 좋을거같습니다.

**Comment by ashwon12** [comment]
@dev-donghwan  참고해서 내용 조금 수정해봐야겠어요! 감사합니당😀

**Comment by jionchu** [comment]
https://jionchu.tistory.com/14

**Comment by junieberry** [comment]
옵저버 패턴
https://junieberry.github.io/android/2021-09-09-ObserverPattern.html
LiveData
https://junieberry.github.io/android/2021-09-10-LiveData.html
